<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.delete.0ebe5a8e-1b95-4e13-8105-b51c68d299ed</name>
   <tag></tag>
   <elementGuidId>a5e4356c-a82d-42c9-8568-08472c1e0101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.6ca9636f-92c3-43c9-9555-d4e41354dfa7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.6ca9636f-92c3-43c9-9555-d4e41354dfa7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8ef8a6b-6455-4ea1-aeec-c302aaf5bc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.6ca9636f-92c3-43c9-9555-d4e41354dfa7</value>
      <webElementGuid>19c60b20-e9ad-49a2-9540-9139a7c1cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4b6268c9-6f0f-4a60-81c3-c5f5cb11b33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>af50d317-fcdc-417b-a17b-0b48113f7713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete Dell USB Wireless Keyboard and Mouse Set- KM3322W, Anti-Fade &amp;amp; Spill-Resistant Keys, up to 36 Month Battery Life, 3Y Advance Exchange Warranty, Black</value>
      <webElementGuid>eca58a37-bb0b-4c41-a8f6-ec67f4e57a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fbd52369-258d-461b-b271-d9f0649ffe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>2a60e603-488f-4571-bd39-cd981c0bb1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-6ca9636f-92c3-43c9-9555-d4e41354dfa7&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>ed72f471-3dc8-47e5-bb2e-b0ee63e7b282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.6ca9636f-92c3-43c9-9555-d4e41354dfa7']</value>
      <webElementGuid>2b4b1ef1-15d5-4d40-bb7d-ab4ef16dd2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-6ca9636f-92c3-43c9-9555-d4e41354dfa7']/div[4]/div/div[3]/div/span[2]/span/input</value>
      <webElementGuid>da41d8fa-9cb4-47ef-bed7-f0904611b2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>459dbd5c-c7b6-4f16-a67a-797cb0f4f256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.6ca9636f-92c3-43c9-9555-d4e41354dfa7' and @type = 'submit']</value>
      <webElementGuid>3032e08b-3f1a-44d8-b219-f1dbf452ca0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
