<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Amazon.in_field-keywords</name>
   <tag></tag>
   <elementGuidId>68fd3c0e-3c44-43bb-95a7-459e5ecdf127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#twotabsearchtextbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='twotabsearchtextbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43ed0dd1-01ac-4414-9147-3cfa4ee56415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85da3d78-498c-4d87-a74b-b3a23ed159f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>twotabsearchtextbox</value>
      <webElementGuid>008fbbe7-35d9-4577-af21-b8f38e7a54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field-keywords</value>
      <webElementGuid>fccd8dd3-4888-438b-b154-6f15bf596af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5fce39ab-9fed-4030-a9c5-2ce0f83e6e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Amazon.in</value>
      <webElementGuid>a1618e3e-c41a-43e0-9168-83d94dc79b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>ba3fe558-1212-471d-a8f1-91924ce0e5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ac47e5ab-0f58-4157-ae34-33fbd876be1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e80843e6-376b-407d-ad2a-3e2d65399d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Amazon.in</value>
      <webElementGuid>a99e6439-8ac7-4b59-b0b4-26de65f80f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cea10079-8dbb-4791-98ab-0861d5d53b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;twotabsearchtextbox&quot;)</value>
      <webElementGuid>a85c0cbc-ce04-4069-ac61-6cc367b49d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='twotabsearchtextbox']</value>
      <webElementGuid>318934ac-db77-4580-babe-33553ef2c93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='nav-search-bar-form']/div[2]/div/input</value>
      <webElementGuid>56c8a88f-4cc2-4e7e-bff1-acc442ac865e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d26f1971-6016-48f4-ab5c-fae86f723b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'twotabsearchtextbox' and @name = 'field-keywords' and @placeholder = 'Search Amazon.in']</value>
      <webElementGuid>6dc0d6a8-a431-470a-adc2-6872b468fe9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
