<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>7d8b2ae8-818e-42dd-9cf5-aeecb172f1cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='NAME_BUTTON']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NAME_BUTTON > span.a-button-inner > a.a-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa0c6a8e-ad5f-4fc8-bdb4-366e10823bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ap/profile/name?ref_=ax_am_landing_change_name&amp;openid.assoc_handle=inflex</value>
      <webElementGuid>eb32a902-fa91-4e72-813c-38ed650343c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit name</value>
      <webElementGuid>72c69f32-fc27-483a-8e2c-02dc18367ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>7cae2dd5-0ba5-4ee4-9ad5-709b6f862d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>d04e7894-315d-4f58-87d1-bd52565c8295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NAME_BUTTON&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>9b432c72-c2e7-4b8c-873a-21740492a4d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='NAME_BUTTON']/span/a</value>
      <webElementGuid>2e197964-73b9-434f-8f96-415ab1bcd405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>92e57962-1513-4da9-9a71-17169245ede9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ap/profile/name?ref_=ax_am_landing_change_name&amp;openid.assoc_handle=inflex')]</value>
      <webElementGuid>5c3ec705-47de-4a24-aa3e-21b4e777e445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/a</value>
      <webElementGuid>6f86ada4-5cbc-43d9-b858-db62f1cfe2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ap/profile/name?ref_=ax_am_landing_change_name&amp;openid.assoc_handle=inflex' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>75d3b760-c6fe-494d-b587-1e135ba6ed52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
